### ISSUE TITLE
`chain.from_iterable` does not play nice inside VSCode

### ISSUE THREAD

**Issue by polyipseity** [maxfischer2781/asyncstdlib#102]
When I simply use `chain.from_iterable()`:
```py
asyncstdlib.chain.from_iterable(...)
```
it claims:
```
Cannot access member "from_iterable" for type "function"
  Member "from_iterable" is unknown
```

Using `itertools.chain_from_iterable()` does not work either:
```py
asyncstdlib.itertools.chain_from_iterable(...)
```
as it reports:
```
Object of type "Definition*" is not callable
```

I have to add a `# type: ignore`, which is unsatisfactory. Is there a better way to work around this on your end?

**Comment by maxfischer2781** [comment]
This is an artefact of `asyncstdlib` defining `chain` as a function instead of a class. I can change it, the standard library `chain` is a class as well.
