### ISSUE TITLE
alru_cache decorator on a class method causes mypy error: Missing positional argument "self"

### ISSUE THREAD

**Issue by atusy** [maxfischer2781/asyncstdlib#104]
Thank you for the amazing project.

I'm trying to apply `alru_cache` on a class method, but mypy raises an error and a note:

```
error: Missing positional argument "self" in call to "f" of "X"  [call-arg]
note: "__call__" is considered instance variable, to make it class variable use ClassVar[...]
```

below is the reproducible example tested with mypy 1.1.1 and asyncstdlib 3.10.5

``` python
from asyncstdlib.functools import lru_cache as alru_cache

class X:
    @alru_cache()
    async def f(self) -> int:
        return 1

    async def g(self) -> int:
        return await self.f()
```

**Comment by maxfischer2781** [comment]
This might take a bit. [The standard library type hints just ignore all arguments](https://github.com/python/typeshed/blob/b6564d976b336ddff962870092ac873a60dfa9b2/stdlib/functools.pyi#L50-L56), making the implicit-`self` case trivially covered. I need to check if it is possible to cover the `self` case explicitly or disable argument checking only for methods.

**Comment by maxfischer2781** [comment]
It looks like it is not possible to stitch things together using `ParamSpec`: https://github.com/python/mypy/issues/13222

**Comment by atusy** [comment]
Wow! Thank you for your hard work.

**Comment by maxfischer2781** [comment]
Looks like I found out how to stitch together `self` and other parameters. Method parameters should fully work with #129.

**Comment by atusy** [comment]
How nice!!
