### ISSUE TITLE
Change in behavior of chain() between 3.10.5 and 3.10.6.

### ISSUE THREAD

**Issue by byllyfish** [maxfischer2781/asyncstdlib#107]
There is a subtle change in behavior introduced in the recent changes to `chain()`. Chain's iterator appears to be escaping from its "scope" when it is interrupted.

Here is an example program that produces different output. I'm using Python 3.11.2, but I don't think the Python version makes much difference.

```python
import asyncio

import asyncstdlib as asl


async def gen1(*args):
    try:
        for i in args:
            yield i
    finally:
        print("FINALLY")


async def main():
    nums = asl.chain(gen1(1, 2, 3))
    nums = asl.takewhile(lambda x: x != 2, nums)

    async for n in nums:
        print(n)

    print("ALL DONE")


asyncio.run(main())
```

## asyncstdlib 3.10.5 (correct output)

```
1
FINALLY
ALL DONE
```

## asyncstdlib 3.10.6 (incorrect output)

```
1
ALL DONE
FINALLY
```

**Comment by byllyfish** [comment]
Here's a construction of `chain` that seems to work better:

```python
class _Chain1:
    def __call__(self, *iterables):
        async def impl():
            for iterable in iterables:
                async with asl.scoped_iter(iterable) as iterator:
                    async for item in iterator:
                        yield item

        return impl()

    # Add other async methods here...

chain = _Chain1()
```

**Comment by maxfischer2781** [comment]
It looks like this is due to a missing `aclose` (which a class implementation needs explicitly). Thanks for the report.

**Comment by byllyfish** [comment]
The fix you committed passes all my tests. Thanks!
