### ISSUE TITLE
[Bug]: Annotated return type of `tee.__iter__` is `Iterator[AnyIterable]` when I think it should be `Iterator[AsyncIterable/-ator]`

### ISSUE THREAD

**Issue by smheidrich** [maxfischer2781/asyncstdlib#151]
### What happened?

The return type of `tee.__iter__` is currently annotated as being `Iterator[AnyIterable[T]]`:

https://github.com/maxfischer2781/asyncstdlib/blob/806e85e1808c8d6c8a8b2accff2349b33e601a36/asyncstdlib/itertools.pyi#L133

Meanwhile, methods like `__getitem__` that ought to return one element of the `Iterator` returned by `__iter__` have an annotated return type of `AsyncIterator[T]`:

https://github.com/maxfischer2781/asyncstdlib/blob/806e85e1808c8d6c8a8b2accff2349b33e601a36/asyncstdlib/itertools.pyi#L130

As `AnyIterable` is just an alias for the union of `Iterable` and `AsyncIterable`, but (AFAICT) `tee` represents a "tuple" of `AsyncIterable`s, I think the return type of `tee.__iter__` should probably be something more like `Iterator[AsyncIterable[T]]`, or better yet `Iterator[AsyncIterator[T]]` to match `__getitem__` exactly.

The latter would also match `tee`'s docs, which state:

>Create n separate asynchronous iterators over iterable

Or am I getting something wrong? :thinking: 

### Minimal Reproducible Example

```python
from typing import Any, AsyncIterable
from asyncstdlib import tee

def f(it: AsyncIterable[Any]) -> None:
  ...

it1, it2 = tee([1, 2, 3], n=2)

f(it1)  # Mypy error:
# Argument 1 to "f" has incompatible type "Iterable[int] | AsyncIterable[int]"; expected "AsyncIterable[Any]"
```

### Request Assignment [Optional]

- [ ] I already understand the cause and want to submit a bugfix.

**Comment by maxfischer2781** [comment]
Thanks for the report. I need to look into whether there was a reason for doing it that way, but looking at it now it certainly seems that you are correct.

**Comment by maxfischer2781** [comment]
Indeed this the annotation is not correct. It should be both `Async…` and `…Iterator`, as `Iterator[AsyncIterator[T]]`.

**Comment by smheidrich** [comment]
Thanks!! :+1:
