### ISSUE TITLE
Add pre-commit script

### ISSUE THREAD

**Issue by mristin** [maxfischer2781/asyncstdlib#31]
I noticed that there is no pre-commit script available. Would you like me to create a PR and introduce a pre-commit script such as [the pre-commit script I wrote for CrossHair](https://github.com/pschanely/CrossHair/blob/master/precommit.py)?

**Comment by maxfischer2781** [comment]
Sorry, I still need to review some pre-commit setups. I would prefer not to commit to a pre-commit hook at this point.

**Comment by mristin** [comment]
Maybe it was not clear from the link: it's not a hook, it's just a Python script that encapsulates what you wrote in `.travis.yml`. So instead of syncing the command in documentation ("run flake, then run black, then run coverage"), you just point the reader to the script ("run precommit.py") and you also execute the same script in `.travis.yml`.

Please confirm again that you'd prefer the unDRY approach before I write the contributing guidelines tonight :).

**Comment by maxfischer2781** [comment]
Misunderstood you somewhat, but still "no" for the time being. ;)
