### ISSUE TITLE
Planned release date for 3.11?

### ISSUE THREAD

**Issue by mristin** [maxfischer2781/asyncstdlib#38]
Hi @maxfischer2781 ,
Have you already planned a release date for 3.11?

I'd like to refer to asyncstdlib from [icontract's documentation on async], but this makes sense only when 3.11 is released. (We also have to use [fastapi-icontract] at work this Wednesday, so it would be great if we could start using asyncstdlib from the begining or at least know when to expect a release to plan for it.)

[icontract's documentation on async]: https://icontract.readthedocs.io/en/latest/async.html

[fastapi-icontract]: https://github.com/mristin/fastapi-icontract

**Comment by maxfischer2781** [comment]
I am currently preparing 3.9.1 which will include both ``apply`` and ``await_each``.

**Comment by maxfischer2781** [comment]
@mristin I've just pushed v3.9.1 to PyPI.

**Comment by mristin** [comment]
@maxfischer2781 Thanks! I'll update the documentation in [icontract].

[icontract]: https://github.com/Parquery/icontract
