### ISSUE TITLE
Publish package on conda-forge

### ISSUE THREAD

**Issue by hechth** [maxfischer2781/asyncstdlib#50]
Would it be possible to make the package available on [conda-forge](https://conda-forge.org/docs/user/contributing.html) so that it is available inside the [conda](https://docs.conda.io/en/latest/) ecosystem?

A detailed description and help of how to get your package to conda-forge is given [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-staging-process) and I'm also happy to support you in case there are any questions!

This would make the package in general available to a wider audience and many more applications.

**Comment by maxfischer2781** [comment]
I do not use conda myself, but am not opposed to publishing the package via conda as well. Will need a few days to prepare the required metadata.

**Comment by maxfischer2781** [comment]
Should be handled via conda-forge/staged-recipes#15664. Let me know if there are any issues.

**Comment by klauer** [comment]
I'm not the original issue reporter, but the conda-forge installation works well for me. 

Thanks for the very useful library (and also adding to the conda-forge ecosystem). 👍

**Comment by maxfischer2781** [comment]
Thanks a lot for checking @klauer and thanks a lot for pushing this @hechth.
