### ISSUE TITLE
Doc typo?

### ISSUE THREAD

**Issue by ludaavics** [maxfischer2781/asyncstdlib#59]
Your doc says the `strict` parameter of `zip` is [new in version 3.10.0.](https://asyncstdlib.readthedocs.io/en/latest/source/api/builtins.html#asyncstdlib.builtins.zip)

At first I thought the doc was ahead of the pypi release, but it seems the parameter is already present in the latest release -- 3.9.2.

Perhaps a typo?

**Comment by maxfischer2781** [comment]
Good catch.

The code is already in the 3.9 versions but it's not "official" yet. I will prepare the 3.10 release soon and as part of that to the final internal review for the new additions.
