### ISSUE TITLE
Add `chunks` or `chunked` functionality

### ISSUE THREAD

**Issue by AIGeneratedUsername** [maxfischer2781/asyncstdlib#92]
Accept both `Iterator` and `AsyncIterator`. Achieve the same as [this code](https://github.com/vxgmichel/aiostream/blob/0e8e84d17791f576803d663d8c818524e7a3725d/aiostream/stream/transform.py#L80) do.

**Comment by maxfischer2781** [comment]
Thanks for the suggestions. However, as far as I can tell there is no equivalent in the standard library. Can you please clarify if I missed it? I'm also no entirely sure whether these are overlapping or distinct chunks.

In the meantime, if anyone needs a recipe to build this themselves, overlapping chunks would be similar to `pairwise`:
```python3
async def pairwise(iterable: AnyIterable[T], n: int) -> AsyncIterator[Tuple[T, ...]]:
    async with ScopedIter(iterable) as async_iter:
        buffer = collections.deque(
            [await anext(async_iter, None) for _ in range(n-1)],
            maxlen=n,
        )
        async for current in async_iter:
            buffer.append(current)
            yield tuple(buffer)
```
Give or take a few typos, I didn't run the code.

**Comment by AIGeneratedUsername** [comment]
I'm sorry to bother you. I will close this issue because as far as I understand the focus of the current package is the standard library, and not adding lots of custom functions outside of the scope.
Of course, someone may try to submit a pull request.
