### ISSUE TITLE
`hasattr` call for attribute being `cached_property` raises `RuntimeWarning`

### ISSUE THREAD

**Issue by alex-kowalczyk** [maxfischer2781/asyncstdlib#99]
Steps to reproduce:
```
import asyncstdlib
import asyncio

class X:
    @asyncstdlib.cached_property
    async def prop(self): 
        await asyncio.sleep(1)
        return True
    
>>> x = X()
>>> hasattr(x, 'prop')
True
<input>:1: RuntimeWarning: coroutine 'CachedProperty._get_attribute' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by maxfischer2781** [comment]
Thanks for the report. I will need to ponder this a bit – it could be fixed by some extra code but a `hasattr` is never meaningful for a `cached_property`. So I'm not entirely sure if the extra cost (maintenance, runtime) is worth it.

**Comment by maxfischer2781** [comment]
This looks worth fixing. `asyncstdlib` uses a helper for the cached value anyway, which should be the more common access to begin with. So adding a helper for the uncommon case should not be harmful.
